name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  shake: ^2.2.0
  flutter_shake_animated: ^0.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/
